"""Updated project structure (database)

Revision ID: 321cca78289d
Revises: a648845c5c2a
Create Date: 2025-03-03 19:46:28.522429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321cca78289d'
down_revision = 'a648845c5c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.drop_constraint('chapters_book_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['book_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('content')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('pages_story_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'chapters', ['chapter_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'projects', ['story_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.drop_constraint('poems_poem_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['poem_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('page_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('poems_poem_id_fkey', 'projects', ['poem_id'], ['id'])

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('pages_story_id_fkey', 'projects', ['story_id'], ['id'])
        batch_op.drop_column('chapter_id')

    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chapters_book_id_fkey', 'projects', ['book_id'], ['id'])

    # ### end Alembic commands ###
