"""Made Page model chapter_id nullable

Revision ID: 48152a61ed87
Revises: 321cca78289d
Create Date: 2025-03-03 22:20:53.524924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48152a61ed87'
down_revision = '321cca78289d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
