"""Added page_number column to poems

Revision ID: 4d977bffebd4
Revises: 2daa61b1a2fb
Create Date: 2025-03-01 23:11:27.897923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d977bffebd4'
down_revision = '2daa61b1a2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poems', schema=None) as batch_op:
        # Step 1: Add column as nullable first
        op.add_column('poems', sa.Column('page_number', sa.Integer(), nullable=True))

        # Step 2: Set default values for existing rows
        op.execute('UPDATE poems SET page_number = 1 WHERE page_number IS NULL')

        # Step 3: Alter column to make it NOT NULL
        op.alter_column('poems', 'page_number', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poems', 'page_number')

    # ### end Alembic commands ###
