"""Changed CreateBooks to Projects and added minor details

Revision ID: a5e2ca9954eb
Revises: 1e54f2d8dd5c
Create Date: 2025-02-17 21:45:24.580212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e2ca9954eb'
down_revision = '1e54f2d8dd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.String(length=50), nullable=False))
        batch_op.drop_column('prject_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prject_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('project_type')

    # ### end Alembic commands ###
