"""Make chapter_number non-nullable

Revision ID: a648845c5c2a
Revises: 4d977bffebd4
Create Date: 2025-03-03 16:01:54.809880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a648845c5c2a'
down_revision = '4d977bffebd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('chapter_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapters', schema=None) as batch_op:
        batch_op.alter_column('chapter_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
