"""Added the datetime functionality

Revision ID: b5f58803c477
Revises: f647ebbd6d85
Create Date: 2025-02-16 20:50:50.787917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = 'b5f58803c477'
down_revision = 'f647ebbd6d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
    
    op.execute("UPDATE create_books SET created_at = NOW();")

    with op.batch_alter_table('create_books', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('create_books', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
